import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'full stack blog app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
